import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  const { status } = useSession();
  if (status === "loading") {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Timeline />
      </div>
    </>
  );
};

export default Home;
